[package]
name = "pdfex"
version = "0.1.0"
edition = "2021"

[dependencies]
pdf2image = "0.1.2"
poppler = "0.5.1"
structopt = "0.3.26"
tesseract = "0.15.1"

[build-dependencies]
pkg-config = "0.3.31"
